// The CSS module types (`*.module.css`, `@/global.css`) that expo-env.d.ts
// provides. That file is generated by `expo start` and gitignored, so a fresh
// clone -- and CI -- type-checked without it and failed. Not named
// expo-env.d.ts: that .gitignore line has no leading slash and would match it here.
/// <reference types="expo/types" />
